src/org/irri/iric/portal/domain/Gene.java
package org.irri.iric.portal.domain;

public interface Gene extends MultiReferenceLocus {

}

src/org/irri/iric/portal/domain/Locus.java
package org.irri.iric.portal.domain;

import java.math.BigDecimal;

/**
 * Locus interface
 * 
 * @author LMansueto
 *
 */
public interface Locus extends Comparable {

	/**
	 * Locus name
	 * 
	 * @return
	 */
	public String getUniquename();

	/**
	 * Chromosome name
	 * 
	 * @return
	 */
	public Long getChr();

	/**
	 * Locus start position
	 * 
	 * @return
	 */
	public Integer getFmin();

	/**
	 * Locus stop position
	 * 
	 * @return
	 */
	public Integer getFmax();

	/**
	 * Strand
	 * 
	 * @return
	 */
	public Integer getStrand();

	/**
	 * contig name
	 * 
	 * @return
	 */
	public String getContig();

	/**
	 * Decription
	 * 
	 * @return
	 */
	public String getDescription();

	public BigDecimal getFeatureId();

	// public String printFields(String delimiter);

	public String getFeatureType();

}

WebRoot/WEB-INF/pages/gene/deleteGene.jsp
<%@page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<jsp:directive.include file="/WEB-INF/sitemesh-decorators/include.jsp"/>
<fmt:setBundle basename="bundles.gene-resources"/>
<html>
<head>
<title>View <fmt:message key="gene.title"/></title>
</head>
<body>
<div id="contentarea">      
	<div id="lb"><div id="rb"><div id="bb"><div id="blc">
	<div id="brc"><div id="tb"><div id="tlc"><div id="trc">
		<div id="content">
			<h1><fmt:message key="gene.title"/> Details</h1>
			<div class="navitem"><a class="button" href="${pageContext.request.contextPath}/indexGene"><span><img src="images/icons/back.gif" /><fmt:message key="navigation.back"/></span></a></div>
		
			<table cellpadding="0" cellspacing="0" id="viewTable">
				<tbody>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.featureid.title"/>:
						</td>
						<td>
							${gene.featureId}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.genefield.title"/>:
						</td>
						<td>
							${gene.geneField}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.uniquename.title"/>:
						</td>
						<td>
							${gene.uniquename}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmin.title"/>:
						</td>
						<td>
							${gene.fmin}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmax.title"/>:
						</td>
						<td>
							${gene.fmax}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.chr.title"/>:
						</td>
						<td>
							${gene.chr}
						&nbsp;
						</td>
					</tr>
				</tbody>
			</table>
			<div class="navitem"><a class="button" href="${pageContext.request.contextPath}/deleteGene?featureIdKey=${gene.featureId}&"><span><img src="images/icons/delete.gif" /><fmt:message key="navigation.delete"/></span></a></div>
			<div class="clear">&nbsp;</div>
		</div>
	</div></div></div></div>
	</div></div></div></div>
</div>
</body>
</html>

WebRoot/WEB-INF/pages/gene/editGene.jsp
<%@page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<jsp:directive.include file="/WEB-INF/sitemesh-decorators/include.jsp"/>
<fmt:setBundle basename="bundles.gene-resources"/>
<html>
<head>
<title>Edit <fmt:message key="gene.title"/></title>
</head>
<body>
<div id="contentarea">      
	<div id="lb"><div id="rb"><div id="bb"><div id="blc">
	<div id="brc"><div id="tb"><div id="tlc"><div id="trc">
	<div id="content">
		<h1><fmt:message key="navigation.edit"/> <fmt:message key="gene.title"/></h1>
		<div class="navitem"><a class="button" href="${pageContext.request.contextPath}/indexGene"><span><img src="images/icons/back.gif" /><fmt:message key="navigation.back"/></span></a></div>
		<form:form action="${pageContext.request.contextPath}/saveGene" method="POST" modelAttribute="gene">
			<table cellpadding="0" cellspacing="0" id="viewTable">
				<tbody>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.featureid.title"/>:
						</td>
						<td>
							<c:choose>
								<c:when test='${newFlag}' >
							<form:input id="gene_featureId" path="featureId" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_featureId",widgetType : "dijit.form.NumberTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.featureid.help"/>", constraints : {places:0}}})); </script>
								</c:when>
								<c:otherwise>
							${gene.featureId}
						&nbsp;
									<form:hidden id="gene_featureId" path="featureId"/>
								</c:otherwise>
							</c:choose>
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.genefield.title"/>:
						</td>
						<td>
							<form:input id="gene_geneField" path="geneField" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_geneField",widgetType : "dijit.form.ValidationTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.genefield.help"/>"}})); </script>
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.uniquename.title"/>:
						</td>
						<td>
							<form:input id="gene_uniquename" path="uniquename" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_uniquename",widgetType : "dijit.form.ValidationTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.uniquename.help"/>"}})); </script>
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmin.title"/>:
						</td>
						<td>
							<form:input id="gene_fmin" path="fmin" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_fmin",widgetType : "dijit.form.NumberTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.fmin.help"/>"}})); </script>
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmax.title"/>:
						</td>
						<td>
							<form:input id="gene_fmax" path="fmax" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_fmax",widgetType : "dijit.form.NumberTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.fmax.help"/>"}})); </script>
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.chr.title"/>:
						</td>
						<td>
							<form:input id="gene_chr" path="chr" cssStyle="width:300px;"/>
							<script type="text/javascript">Spring.addDecoration(new Spring.ElementDecoration({elementId : "gene_chr",widgetType : "dijit.form.ValidationTextBox",widgetAttrs : {promptMessage: "<fmt:message key="gene.chr.help"/>"}})); </script>
						</td>
					</tr>
				</tbody>
			</table>
			<span class="inputbutton"><input class="savebutton" id="save" type="submit" value="<fmt:message key="navigation.save"/>"/></span>
			<script type="text/javascript">Spring.addDecoration(new Spring.ValidateAllDecoration({elementId:'save', event:'onclick'}));</script>
		</form:form>
		<div class="clear">&nbsp;</div>
	</div>
	</div></div></div></div>
	</div></div></div></div>
</div>
</body>
</html>

WebRoot/WEB-INF/pages/gene/listGenes.jsp
<%@ page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<jsp:directive.include file="/WEB-INF/sitemesh-decorators/include.jsp"/>
<fmt:setBundle basename="bundles.gene-resources"/>
<html>
<head>
<title>List <fmt:message key="gene.title"/>s</title>
</head>
<body>
<div id="contentarea" >
	<div id="lb"><div id="rb"><div id="bb"><div id="blc">
	<div id="brc"><div id="tb"><div id="tlc"><div id="trc">
	<div id="content">
		<h1>Manage <fmt:message key="gene.title"/>s</h1>
		<div class="navitem"><a class="button" href="${pageContext.request.contextPath}/newGene"><span><img src="${pageContext.request.contextPath}/images/icons/new.gif" /><fmt:message key="navigation.new"/> <fmt:message key="gene.title"/></span></a></div>
		<div id="tablewrapper">
		<table id="listTable" cellpadding="0" cellspacing="0">
			<thead>
				<tr>
					<th class="thead">&nbsp;</th>
					<th class="thead"><fmt:message key="gene.featureid.title"/></th>
					<th class="thead"><fmt:message key="gene.genefield.title"/></th>
					<th class="thead"><fmt:message key="gene.uniquename.title"/></th>
					<th class="thead"><fmt:message key="gene.fmin.title"/></th>
					<th class="thead"><fmt:message key="gene.fmax.title"/></th>
					<th class="thead"><fmt:message key="gene.chr.title"/></th>
				</tr>
			</thead>
			<tbody>
				<c:forEach items="${genes}" var="current" varStatus="i">
					<c:choose>
						<c:when test="${(i.count) % 2 == 0}">
		    				<c:set var="rowclass" value="rowtwo"/>
						</c:when>
						<c:otherwise>
		    				<c:set var="rowclass" value="rowone"/>
						</c:otherwise>
					</c:choose>	
				<tr class="${rowclass}">
					<td nowrap="nowrap" class="tabletd">
						<a title="<fmt:message key="navigation.view" />" href="${pageContext.request.contextPath}/selectGene?featureIdKey=${current.featureId}&"><img src="images/icons/view.gif" /></a>
						<a title="<fmt:message key="navigation.edit" />" href="${pageContext.request.contextPath}/editGene?featureIdKey=${current.featureId}&"><img src="images/icons/edit.gif" /></a>
						<a title="<fmt:message key="navigation.delete" />" href="${pageContext.request.contextPath}/confirmDeleteGene?featureIdKey=${current.featureId}&"><img src="images/icons/delete.gif" /></a>
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.featureId}
						&nbsp;
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.geneField}
						&nbsp;
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.uniquename}
						&nbsp;
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.fmin}
						&nbsp;
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.fmax}
						&nbsp;
					</td>
					<td nowrap="nowrap" class="tabletd">
						
							${current.chr}
						&nbsp;
					</td>
				</tr>
				</c:forEach>
			</tbody>
		</table>
		</div>
	</div>
	</div></div></div></div>
	</div></div></div></div>
</div>
</body>
</html>

WebRoot/WEB-INF/pages/gene/menu.jsp
<%@page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<jsp:directive.include file="/WEB-INF/sitemesh-decorators/include.jsp"/>
<fmt:setBundle basename="bundles.gene-resources"/>
<a class="button" href="${pageContext.request.contextPath}/indexGene"><span><img src="images/icons/view.gif" /><fmt:message key="navigation.view"/> <fmt:message key="gene.title"/>s</span></a>

WebRoot/WEB-INF/pages/gene/viewGene.jsp
<%@page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<jsp:directive.include file="/WEB-INF/sitemesh-decorators/include.jsp"/>
<fmt:setBundle basename="bundles.gene-resources"/>
<html>
<head>
<title>View <fmt:message key="gene.title"/></title>
</head>
<body>
<div id="contentarea">      
	<div id="lb"><div id="rb"><div id="bb"><div id="blc">
	<div id="brc"><div id="tb"><div id="tlc"><div id="trc">
		<div id="content">
			<h1><fmt:message key="gene.title"/> Details</h1>
			<div class="navitem"><a class="button" href="${pageContext.request.contextPath}/indexGene"><span><img src="images/icons/back.gif" /><fmt:message key="navigation.back"/></span></a></div>	
			<table cellpadding="0" cellspacing="0" id="viewTable">
				<tbody>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.featureid.title"/>:
						</td>
						<td>
							${gene.featureId}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.genefield.title"/>:
						</td>
						<td>
							${gene.geneField}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.uniquename.title"/>:
						</td>
						<td>
							${gene.uniquename}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmin.title"/>:
						</td>
						<td>
							${gene.fmin}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.fmax.title"/>:
						</td>
						<td>
							${gene.fmax}
						&nbsp;
						</td>
					</tr>
					<tr>
						<td class="label" valign="top">
							<fmt:message key="gene.chr.title"/>:
						</td>
						<td>
							${gene.chr}
						&nbsp;
						</td>
					</tr>
				</tbody>
			</table>
			<div class="clear">&nbsp;</div>
		</div>
	</div></div></div></div>
	</div></div></div></div>
</div>
</body>
</html>